- name: Deploy a CentOS Droplet in Digital Ocean Cloud
  hosts: localhost
  collections: 
    - community.digitalocean
  tasks:
    - name: Create a CentOS 8 Droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        name: centos-8
        oauth_token: "{{ digitalocean_api_key }}"
        size: 2gb
        region: blr1
        image: centos-8-x64
        wait_timeout: 500
        ssh_keys: [ 28853132 ]
      register: my_droplet

    - debug:
        msg: "The CentOS instance is available at the public IP - {{ my_droplet.data.ip_address }}"
